### ISSUE TITLE
Error during setup of component hass_cozylife_local_pull

### ISSUE THREAD

**Issue by miguelpucela** [cozylife/hass_cozylife_local_pull#10]
I get an error during restart of HA and cozylife entities does not appear. It worked previously (maybe before last update of HA).

Versions:
Home Assistant 2023.1.0
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230104.0 - latest

The error log is:

This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/hass_cozylife_local_pull/tcp_client.py:50
Integration: hass_cozylife_local_pull (documentation)
First occurred: 2:18:45 AM (1 occurrences)
Last logged: 2:18:45 AM

Error during setup of component hass_cozylife_local_pull
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 253, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hass_cozylife_local_pull/__init__.py", line 23, in setup
    'tcp_client': [tcp_client(item) for item in ip],
  File "/config/custom_components/hass_cozylife_local_pull/__init__.py", line 23, in <listcomp>
    'tcp_client': [tcp_client(item) for item in ip],
  File "/config/custom_components/hass_cozylife_local_pull/tcp_client.py", line 50, in __init__
    s.connect((self._ip, self._port))
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by cozylife** [comment]
Hi.
Your problem now is that the tcp connection fails, when I have time I will get the check information.



***@***.*** 
Website:https://cozylife.app
FAQ:http://api-us.doiting.com/web/app/faq
 
From: miguelpucela
Date: 2023-01-06 09:28
To: cozylife/hass_cozylife_local_pull
CC: Subscribed
Subject: [cozylife/hass_cozylife_local_pull] Error during setup of component hass_cozylife_local_pull (Issue #10)
I get an error during restart of HA and cozylife entities does not appear. It worked previously (maybe before last update of HA).
Versions:
Home Assistant 2023.1.0
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230104.0 - latest
The error log is:
This error originated from a custom integration.
Logger: homeassistant.setup
Source: custom_components/hass_cozylife_local_pull/tcp_client.py:50
Integration: hass_cozylife_local_pull (documentation)
First occurred: 2:18:45 AM (1 occurrences)
Last logged: 2:18:45 AM
Error during setup of component hass_cozylife_local_pull
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 253, in _async_setup_component
result = await task
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/hass_cozylife_local_pull/init.py", line 23, in setup
'tcp_client': [tcp_client(item) for item in ip],
File "/config/custom_components/hass_cozylife_local_pull/init.py", line 23, in 
'tcp_client': [tcp_client(item) for item in ip],
File "/config/custom_components/hass_cozylife_local_pull/tcp_client.py", line 50, in init
s.connect((self._ip, self._port))
ConnectionRefusedError: [Errno 111] Connection refused
