### ISSUE TITLE
Error during setup of component hass_cozylife_local_pull

### ISSUE THREAD

**Issue by miguel-victor-tic** [cozylife/hass_cozylife_local_pull#15]
Logger: homeassistant.setup
Source: custom_components/hass_cozylife_local_pull/tcp_client.py:50
Integration: hass_cozylife_local_pull ([documentation](https://github.com/cozylife/hass_cozylife_local_pull))
First occurred: 23:33:56 (1 occurrences)
Last logged: 23:33:56

Error during setup of component hass_cozylife_local_pull
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 256, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hass_cozylife_local_pull/__init__.py", line 23, in setup
    'tcp_client': [tcp_client(item) for item in ip],
  File "/config/custom_components/hass_cozylife_local_pull/__init__.py", line 23, in <listcomp>
    'tcp_client': [tcp_client(item) for item in ip],
  File "/config/custom_components/hass_cozylife_local_pull/tcp_client.py", line 50, in __init__
    s.connect((self._ip, self._port))
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by miguel-victor-tic** [comment]
![Capturar](https://user-images.githubusercontent.com/60945692/235279862-7667ab2a-dc18-46c0-b6e0-1167581aa66e.PNG)
![Capturar2](https://user-images.githubusercontent.com/60945692/235279863-7d023a48-7766-4f3e-a0c4-6b4005cd02e2.PNG)
![Capturar3](https://user-images.githubusercontent.com/60945692/235279864-a5187bc5-abf8-4790-905a-ae0dcaa9c50d.PNG)
![Capturar4](https://user-images.githubusercontent.com/60945692/235279865-3090064a-5f87-48c6-907e-357b8192c6c7.PNG)

**Comment by rezendea** [comment]
I am having the exact same problem, any lucky on any solution? Apparently the plugin author doesn't take too much time answering the issues here at github...

**Comment by jenskaesler** [comment]
Hello together,

I have had exactly the same error message. After some research I found a workarround which is working within the last 5 core updates without any error message.

I have change the following.

1. Go to your custom components folder and the subfolder hass_cozylife_local_pull
2. Open the file udp_discover.py and change the following section as shown in the screenshot: 

![image](https://github.com/cozylife/hass_cozylife_local_pull/assets/52004672/b2e3c731-46ca-4238-913e-415ab01b3cf8)

3. Do exactly the same in the file test.py
4. Restart HA

Since these changes I don´t receive the error messages again. But it could be that HA is not able to contact the device. In my case the DHCP lease was expired. It seems that HA only discover (or rediscover) the cozylife devices only on startup. So in such case a simple restart of HA could solve the problem and the device is reachable again.

Hope this information could help you to solve your issue too. 

Cheers Jens

**Comment by cozylife** [comment]
> Hello together,
> 
> I have had exactly the same error message. After some research I found a workarround which is working within the last 5 core updates without any error message.
> 
> I have change the following.
> 
>     1. Go to your custom components folder and the subfolder hass_cozylife_local_pull
> 
>     2. Open the file udp_discover.py and change the following section as shown in the screenshot:
> 
> 
> ![image](https://user-images.githubusercontent.com/52004672/262176847-b2e3c731-46ca-4238-913e-415ab01b3cf8.png)
> 
>     3. Do exactly the same in the file test.py
> 
>     4. Restart HA
> 
> 
> Since these changes I don´t receive the error messages again. But it could be that HA is not able to contact the device. In my case the DHCP lease was expired. It seems that HA only discover (or rediscover) the cozylife devices only on startup. So in such case a simple restart of HA could solve the problem and the device is reachable again.
> 
> Hope this information could help you to solve your issue too.
> 
> Cheers Jens

Hello.
Can you submit a PR?
