### ISSUE TITLE
Error Log!

### ISSUE THREAD

**Issue by soubhik-khan** [cozylife/hass_cozylife_local_pull#3]
Saw this error a couple of times in home assistant log 

"Updating state for light.cozylife_color_temperature_lamp (<class 'custom_components.hass_cozylife_local_pull.light.CozyLifeLight'>) took 2.332 seconds. Please report it to the custom component author."

**Comment by soubhik-khan** [comment]
one more.. 

Logger: homeassistant
Source: custom_components/hass_cozylife_local_pull/tcp_client.py:182
Integration: cozylife demo (documentation)
First occurred: 4:41:27 PM (861 occurrences)
Last logged: 11:51:28 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 734, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 492, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 511, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 935, in state
    return STATE_ON if self.is_on else STATE_OFF
  File "/config/custom_components/hass_cozylife_local_pull/light.py", line 150, in is_on
    self._refresh_state()
  File "/config/custom_components/hass_cozylife_local_pull/light.py", line 125, in _refresh_state
    self._state = self._tcp_client.query()
  File "/config/custom_components/hass_cozylife_local_pull/tcp_client.py", line 233, in query
    return self._send_receiver(CMD_QUERY, {})
  File "/config/custom_components/hass_cozylife_local_pull/tcp_client.py", line 182, in _send_receiver
    self._connect.send(self._get_package(cmd, payload))
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by cozylife** [comment]
Hi.
Intergation currently does not support reconnection, we will support this function in subsequent versions. 



***@***.***
 
From: Soubhik (Soubhik_sk83)
Date: 2022-02-02 15:56
To: cozylife/hass_cozylife_local_pull
CC: Subscribed
Subject: Re: [cozylife/hass_cozylife_local_pull] Error Log! (Issue #3)
one more..
Logger: homeassistant
Source: custom_components/hass_cozylife_local_pull/tcp_client.py:182
Integration: cozylife demo (documentation)
First occurred: 4:41:27 PM (861 occurrences)
Last logged: 11:51:28 PM
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 734, in _update_entity_states
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 492, in async_update_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state
state = self._stringify_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 511, in _stringify_state
if (state := self.state) is None:
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 935, in state
return STATE_ON if self.is_on else STATE_OFF
File "/config/custom_components/hass_cozylife_local_pull/light.py", line 150, in is_on
self._refresh_state()
File "/config/custom_components/hass_cozylife_local_pull/light.py", line 125, in _refresh_state
self._state = self._tcp_client.query()
File "/config/custom_components/hass_cozylife_local_pull/tcp_client.py", line 233, in query
return self._send_receiver(CMD_QUERY, {})
File "/config/custom_components/hass_cozylife_local_pull/tcp_client.py", line 182, in _send_receiver
self._connect.send(self._get_package(cmd, payload))
ConnectionResetError: [Errno 104] Connection reset by peer
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
