### ISSUE TITLE
Erro no Log

### ISSUE THREAD

**Issue by nandoap** [cozylife/hass_cozylife_local_pull#7]
por gentileza, conseguiria me ajudar com o erro abaixo:
esta funcionando porem depois da atualização do HA acusou esses erros.

Error during setup of component hass_cozylife_local_pull
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hass_cozylife_local_pull/__init__.py", line 23, in setup
    'tcp_client': [tcp_client(item) for item in ip],
  File "/config/custom_components/hass_cozylife_local_pull/__init__.py", line 23, in <listcomp>
    'tcp_client': [tcp_client(item) for item in ip],
  File "/config/custom_components/hass_cozylife_local_pull/tcp_client.py", line 50, in __init__
    s.connect((self._ip, self._port))
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by cozylife** [comment]
Oi.
Pode ser que seu roteador não ative o acesso à intranet TCP.
Se você tiver certeza de que seu roteador ativou o acesso à intranet, sugiro que reinicie o haas.
